CREATE TABLE IF NOT EXISTS site_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  brand_name VARCHAR(120) NOT NULL,
  tagline VARCHAR(180) NOT NULL,
  hero_title VARCHAR(180) NOT NULL,
  hero_subtitle TEXT NOT NULL,
  about_title VARCHAR(180) NOT NULL DEFAULT 'Quem somos',
  about_text TEXT NULL,
  about_image_url TEXT NULL,
  whatsapp VARCHAR(30) NOT NULL,
  instagram VARCHAR(120) NULL,
  facebook VARCHAR(160) NULL,
  tiktok VARCHAR(160) NULL,
  contact_email VARCHAR(160) NULL,
  address VARCHAR(220) NULL,
  business_hours VARCHAR(160) NULL,
  footer_note TEXT NULL,
  logo_url TEXT NULL,
  hero_image_url TEXT NULL,
  primary_color VARCHAR(20) NOT NULL DEFAULT '#0e7c7b',
  accent_color VARCHAR(20) NOT NULL DEFAULT '#d45070',
  background_color VARCHAR(20) NOT NULL DEFAULT '#fbfaf7',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT single_settings_row CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  category VARCHAR(80) NOT NULL,
  image_url TEXT NULL,
  stock_status ENUM('available', 'made_to_order', 'sold_out') NOT NULL DEFAULT 'available',
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_images (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  image_url TEXT NOT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_product_images_product (product_id),
  CONSTRAINT fk_product_images_product
    FOREIGN KEY (product_id) REFERENCES products(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS offers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  discount_label VARCHAR(80) NOT NULL,
  image_url TEXT NULL,
  starts_at DATE NULL,
  ends_at DATE NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
